defaults: &defaults
  canonical_hostname: "soundcampaign.com"
  campaign_email: "campaign@soundcampaign.com"
  contact_email:  "support@soundcampaign.com"
  contact_address: |
    Brugstraat 77
    6131 AC Sittard
    The Netherlands
  urls:
    blog: "http://blog.soundcampaign.com/"
    facebook: "https://www.facebook.com/SoundCampaign"
    twitter: "https://twitter.com/soundcampaign_"

development:
  <<: *defaults
  canonical_hostname: "soundcampaign.dev"

production:
  <<: *defaults

test:
  <<: *defaults
