defaults: &defaults
  contact_email: "mail@soundcampaign.com"
  canonical_hostname: "soundcampaign.com"
  contact_address: |
    Sesamstraat 111
    Maastricht
  urls:
    blog: "http://blog.soundcampaign.com/"
    facebook: "https://www.facebook.com/SoundCampaign"
    twitter: "https://twitter.com/soundcampaign_"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
