#!/usr/bin/env bash

heroku pgbackups:capture
curl -o db/latest.dump `heroku pgbackups:url`
pg_restore --verbose --clean --no-acl --no-owner -h localhost -d soundcampaign_development db/latest.dump
rm db/latest.dump
